export const payFiEscrowAbi = [
  {
    type: "function",
    name: "createAndDeposit",
    inputs: [
      { name: "merchant_", type: "address" },
      { name: "asset_", type: "address" },
      { name: "amountTotal_", type: "uint128" },
      { name: "amountPerLesson_", type: "uint128" },
      { name: "maxReleases_", type: "uint16" },
      { name: "durationSeconds_", type: "uint64" },
      { name: "agreementHash_", type: "bytes32" },
      { name: "disputeModule_", type: "address" },
    ],
    outputs: [{ name: "id", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "releaseBySignatures",
    inputs: [
      { name: "escrowId", type: "uint256" },
      { name: "amount", type: "uint256" },
      { name: "userSig", type: "bytes" },
      { name: "merchantSig", type: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "refund",
    inputs: [{ name: "escrowId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "escrows",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "user", type: "address" },
      { name: "merchant", type: "address" },
      { name: "asset", type: "address" },
      { name: "amountTotal", type: "uint128" },
      { name: "amountPerLesson", type: "uint128" },
      { name: "maxReleases", type: "uint16" },
      { name: "releaseCount", type: "uint16" },
      { name: "releasedTotal", type: "uint128" },
      { name: "expiresAt", type: "uint64" },
      { name: "status", type: "uint8" },
      { name: "releaseNonce", type: "uint256" },
      { name: "agreementHash", type: "bytes32" },
      { name: "disputeModule", type: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "releaseDigest",
    inputs: [
      { name: "escrowId", type: "uint256" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "EscrowCreated",
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "user", type: "address", indexed: true },
      { name: "merchant", type: "address", indexed: true },
      { name: "asset", type: "address", indexed: false },
      { name: "amountTotal", type: "uint256", indexed: false },
      { name: "expiresAt", type: "uint64", indexed: false },
      { name: "agreementHash", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Released",
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "nonce", type: "uint256", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Refunded",
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "user", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
] as const;
